kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: api-server
  namespace: web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
      - name: api-server
        image: eventyay/nextgen-api-server:latest
        command: ["/bin/sh","-c"]
        args: ["./kubernetes/run.sh"]
        livenessProbe:
          httpGet:
            path: /health-check/
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 1
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: C_FORCE_ROOT
          value: 'true'
        - name: PYTHONUNBUFFERED
          value: 'TRUE'
        - name: DEPLOYMENT
          value: 'api'
        - name: FORCE_SSL
          value: 'yes'
      restartPolicy: Always
