apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: nginx-ingress
  annotations:
    service.beta.kubernetes.io/external-traffic: "OnlyLocal"
spec:
  type: LoadBalancer
  loadBalancerIP: '35.185.193.151'
  ports:
  - port: 80
    name: http
  - port: 443
    name: https
  selector:
    app: nginx
